/**
 * ...
 * @author sirmax2
 */
class wot.utils.VehicleInfoData
{
    public static var data:Object = {
        // unknown
/*
*/

        // level 1
        ussr_MS_1:                      { tiers: [ 1, 2 ],   premium: false, name: null },
        germany_Ltraktor:               { tiers: [ 1, 2 ],   premium: false, name: null },
        usa_T1_Cunningham:              { tiers: [ 1, 2 ],   premium: false, name: null },
        france_RenaultFT:               { tiers: [ 1, 2 ],   premium: false, name: null },
        uk_GB01_Medium_Mark_I:          { tiers: [ 1, 2 ],   premium: false, name: null },
        china_Ch06_Renault_NC31:        { tiers: [ 1, 2 ],   premium: false, name: null },

        // level 2
        ussr_BT_2:                      { tiers: [ 2, 3 ],   premium: false, name: null },
        ussr_T_26:                      { tiers: [ 2, 3 ],   premium: false, name: null },
        ussr_Tetrarch_LL:               { tiers: [ 2, 3 ],   premium: true,  name: null },
        germany_H39_captured:           { tiers: [ 2, 3 ],   premium: true,  name: null },
        germany_Pz35t:                  { tiers: [ 2, 3 ],   premium: false, name: null },
        germany_PzII:                   { tiers: [ 2, 3 ],   premium: false, name: null },
        usa_M2_lt:                      { tiers: [ 2, 3 ],   premium: false, name: null },
        usa_T1_E6:                      { tiers: [ 2, 3 ],   premium: true,  name: null },
        france_D1:                      { tiers: [ 2, 3 ],   premium: false, name: null },
        france_Hotchkiss_H35:           { tiers: [ 2, 3 ],   premium: false, name: null },
        uk_GB03_Cruiser_Mk_I:           { tiers: [ 2, 3 ],   premium: false, name: null },
        uk_GB58_Cruiser_Mk_III:         { tiers: [ 2, 3 ],   premium: false, name: null },
        china_Ch07_Vickers_MkE_Type_BT26:{ tiers:[ 2, 3 ],   premium: false, name: null },
        usa_T2_med:                     { tiers: [ 2, 3 ],   premium: false, name: null },
        uk_GB05_Vickers_Medium_Mk_II:   { tiers: [ 2, 3 ],   premium: false, name: null },
        ussr_AT_1:                      { tiers: [ 2, 3 ],   premium: false, name: null },
        germany_PanzerJager_I:          { tiers: [ 2, 3 ],   premium: false, name: null },
        usa_T18:                        { tiers: [ 2, 3 ],   premium: false, name: null },
        france_RenaultFT_AC:            { tiers: [ 2, 3 ],   premium: false, name: null },
        ussr_SU_18:                     { tiers: [ 3, 4 ],   premium: false, name: null },
        usa_T57:                        { tiers: [ 3, 4 ],   premium: false, name: null },
        france_RenaultBS:               { tiers: [ 3, 4 ],   premium: false, name: null },

        // level 3
        ussr_BT_7:                      { tiers: [ 3, 5 ],   premium: false, name: null },
        ussr_T_46:                      { tiers: [ 3, 5 ],   premium: false, name: null },
        germany_Pz38t:                  { tiers: [ 3, 5 ],   premium: false, name: null },
        germany_PzII_Luchs:             { tiers: [ 3, 5 ],   premium: false, name: null },
        germany_PzIII_A:                { tiers: [ 3, 5 ],   premium: false, name: null },
        germany_T_15:                   { tiers: [ 3, 5 ],   premium: true,  name: null },
        usa_M22_Locust:                 { tiers: [ 3, 5 ],   premium: true,  name: null },
        usa_M3_Stuart:                  { tiers: [ 3, 5 ],   premium: false, name: null },
        usa_MTLS_1G14:                  { tiers: [ 3, 5 ],   premium: true,  name: null },
        france_AMX38:                   { tiers: [ 3, 5 ],   premium: false, name: null },
        uk_GB59_Cruiser_Mk_IV:          { tiers: [ 3, 5 ],   premium: false, name: null },
        uk_GB69_Cruiser_Mk_II:          { tiers: [ 3, 5 ],   premium: false, name: null },
        china_Ch08_Type97_Chi_Ha:       { tiers: [ 3, 5 ],   premium: false, name: null },
        germany_S35_captured:           { tiers: [ 3, 5 ],   premium: true,  name: null },
        usa_M2_med:                     { tiers: [ 3, 5 ],   premium: false, name: null },
        france_D2:                      { tiers: [ 3, 5 ],   premium: false, name: null },
        uk_GB06_Vickers_Medium_Mk_III:  { tiers: [ 3, 5 ],   premium: false, name: null },
        ussr_SU_76:                     { tiers: [ 3, 5 ],   premium: false, name: null },
        germany_G20_Marder_II:          { tiers: [ 3, 5 ],   premium: false, name: null },
        usa_T82:                        { tiers: [ 3, 5 ],   premium: false, name: null },
        france_FCM_36Pak40:             { tiers: [ 3, 5 ],   premium: true,  name: null },
        france_RenaultUE57:             { tiers: [ 3, 5 ],   premium: false, name: null },
        ussr_SU_26:                     { tiers: [ 4, 6 ],   premium: false, name: null },
        germany_Sturmpanzer_II:         { tiers: [ 4, 6 ],   premium: false, name: null },
        germany_Wespe:                  { tiers: [ 4, 6 ],   premium: false, name: null },
        usa_M37:                        { tiers: [ 4, 6 ],   premium: false, name: null },
        france_Lorraine39_L_AM:         { tiers: [ 4, 6 ],   premium: false, name: null },

        // level 4
        ussr_A_20:                      { tiers: [ 4, 8 ],   premium: false, name: null },
        germany_Pz38_NA:                { tiers: [ 4, 8 ],   premium: false, name: null },
        usa_M5_Stuart:                  { tiers: [ 4, 8 ],   premium: false, name: null },
        uk_GB04_Valentine:              { tiers: [ 4, 8 ],   premium: false, name: null },
        uk_GB60_Covenanter:             { tiers: [ 4, 8 ],   premium: false, name: null },
        china_Ch09_M5:                  { tiers: [ 4, 8 ],   premium: false, name: null },
        ussr_T_28:                      { tiers: [ 4, 6 ],   premium: false, name: null },
        germany_PzIII:                  { tiers: [ 4, 6 ],   premium: false, name: null },
        usa_M3_Grant:                   { tiers: [ 4, 6 ],   premium: false, name: null },
        uk_GB07_Matilda:                { tiers: [ 4, 6 ],   premium: false, name: null },
        france_B1:                      { tiers: [ 4, 5 ],   premium: false, name: null },
        ussr_GAZ_74b:                   { tiers: [ 4, 6 ],   premium: false, name: null },
        germany_Hetzer:                 { tiers: [ 4, 6 ],   premium: false, name: null },
        usa_M8A1:                       { tiers: [ 4, 6 ],   premium: false, name: null },
        usa_T40:                        { tiers: [ 4, 6 ],   premium: false, name: null },
        france_Somua_Sau_40:            { tiers: [ 4, 6 ],   premium: false, name: null },
        ussr_SU_5:                      { tiers: [ 5, 8 ],   premium: false, name: null },
        germany_Grille:                 { tiers: [ 5, 8 ],   premium: false, name: null },
        usa_M7_Priest:                  { tiers: [ 5, 8 ],   premium: false, name: null },
        france_AMX_105AM:               { tiers: [ 5, 8 ],   premium: false, name: null },

        // level 5
        ussr_T_50_2:                    { tiers: [ 7, 12 ],  premium: false, name: null },
        germany_VK2801:                 { tiers: [ 7, 12 ],  premium: false, name: null },
        usa_M24_Chaffee:                { tiers: [ 7, 12 ],  premium: false, name: null },
        uk_GB20_Crusader:               { tiers: [ 7, 12 ],  premium: false, name: null },
        ussr_T_34:                      { tiers: [ 5, 7 ],   premium: false, name: null },
        germany_PzIII_IV:               { tiers: [ 5, 7 ],   premium: false, name: null },
        germany_PzIV:                   { tiers: [ 5, 7 ],   premium: false, name: null },
        germany_T_25:                   { tiers: [ 5, 7 ],   premium: true,  name: null },
        usa_M4_Sherman:                 { tiers: [ 5, 7 ],   premium: false, name: null },
        usa_M7_med:                     { tiers: [ 5, 7 ],   premium: false, name: null },
        usa_Ram_II:                     { tiers: [ 5, 7 ],   premium: true,  name: null },
        china_Ch21_T34:                 { tiers: [ 5, 7 ],   premium: false, name: null },
        ussr_KV:                        { tiers: [ 5, 7 ],   premium: false, name: null },
        ussr_KV1:                       { tiers: [ 5, 7 ],   premium: false, name: null },
        usa_T1_hvy:                     { tiers: [ 5, 7 ],   premium: false, name: null },
        france_BDR_G1B:                 { tiers: [ 5, 7 ],   premium: false, name: null },
        uk_GB08_Churchill_I:            { tiers: [ 5, 7 ],   premium: false, name: null },
        ussr_SU_85I:                    { tiers: [ 5, 7 ],   premium: true,  name: null },
        ussr_SU_85:                     { tiers: [ 5, 7 ],   premium: false, name: null },
        germany_StuGIII:                { tiers: [ 5, 7 ],   premium: false, name: null },
        usa_M10_Wolverine:              { tiers: [ 5, 7 ],   premium: false, name: null },
        usa_T49:                        { tiers: [ 5, 7 ],   premium: false, name: null },
        france_S_35CA:                  { tiers: [ 5, 7 ],   premium: false, name: null },
        ussr_SU_8:                      { tiers: [ 7, 9 ],   premium: false, name: null },
        germany_Hummel:                 { tiers: [ 7, 9 ],   premium: false, name: null },
        usa_M41:                        { tiers: [ 7, 9 ],   premium: false, name: null },
        france_AMX_13F3AM:              { tiers: [ 7, 9 ],   premium: false, name: null },

        // level 6
        usa_T21:                        { tiers: [ 7, 11 ],  premium: false, name: null },
        france_AMX_12t:                 { tiers: [ 7, 11 ],  premium: false, name: null },
        china_Ch15_59_16:               { tiers: [ 7, 11 ],  premium: false, name: null },
        ussr_T_34_85:                   { tiers: [ 6, 8 ],   premium: false, name: null },
        germany_VK3001H:                { tiers: [ 6, 8 ],   premium: false, name: null },
        germany_VK3001P:                { tiers: [ 6, 8 ],   premium: false, name: null },
        germany_VK3601H:                { tiers: [ 6, 8 ],   premium: false, name: null },
        usa_M4A3E8_Sherman:             { tiers: [ 6, 8 ],   premium: false, name: null },
        usa_Sherman_Jumbo:              { tiers: [ 6, 8 ],   premium: false, name: null },
        uk_GB21_Cromwell:               { tiers: [ 6, 8 ],   premium: false, name: null },
        china_Ch20_Type58:              { tiers: [ 6, 8 ],   premium: false, name: null },
        ussr_KV_1s:                     { tiers: [ 6, 8 ],   premium: false, name: null },
        ussr_KV2:                       { tiers: [ 6, 8 ],   premium: false, name: null },
        ussr_T150:                      { tiers: [ 6, 8 ],   premium: false, name: null },
        usa_M6:                         { tiers: [ 6, 8 ],   premium: false, name: null },
        france_ARL_44:                  { tiers: [ 6, 8 ],   premium: false, name: null },
        uk_GB09_Churchill_VII:          { tiers: [ 6, 8 ],   premium: false, name: null },
        ussr_SU_100:                    { tiers: [ 6, 8 ],   premium: false, name: null },
        germany_DickerMax:              { tiers: [ 6, 8 ],   premium: true,  name: null },
        germany_JagdPzIV:               { tiers: [ 6, 8 ],   premium: false, name: null },
        usa_M18_Hellcat:                { tiers: [ 6, 8 ],   premium: false, name: null },
        usa_M36_Slagger:                { tiers: [ 6, 8 ],   premium: false, name: null },
        france_ARL_V39:                 { tiers: [ 6, 8 ],   premium: false, name: null },
        ussr_S_51:                      { tiers: [ 9, 10 ],  premium: false, name: null },
        ussr_SU_14:                     { tiers: [ 9, 10 ],  premium: false, name: null },
        germany_G_Panther:              { tiers: [ 9, 10 ],  premium: false, name: null },
        usa_M12:                        { tiers: [ 9, 10 ],  premium: false, name: null },
        france_Lorraine155_50:          { tiers: [ 9, 10 ],  premium: false, name: null },

        // level 7
        usa_T71:                        { tiers: [ 8, 11 ],  premium: false, name: null },
        france_AMX_13_75:               { tiers: [ 8, 11 ],  premium: false, name: null },
        china_Ch02_Type62:              { tiers: [ 8, 11 ],  premium: true,  name: null },
        china_Ch16_WZ_131:              { tiers: [ 8, 11 ],  premium: false, name: null },
        ussr_KV_13:                     { tiers: [ 7, 9 ],   premium: false, name: null },
        ussr_T_43:                      { tiers: [ 7, 9 ],   premium: false, name: null },
        germany_PzV:                    { tiers: [ 7, 9 ],   premium: false, name: null },
        germany_VK3002DB:               { tiers: [ 7, 9 ],   premium: false, name: null },
        usa_T20:                        { tiers: [ 7, 9 ],   premium: false, name: null },
        uk_GB22_Comet:                  { tiers: [ 7, 9 ],   premium: false, name: null },
        china_Ch04_T34_1:               { tiers: [ 7, 9 ],   premium: false, name: null },
        ussr_IS:                        { tiers: [ 7, 9 ],   premium: false, name: null },
        ussr_KV_3:                      { tiers: [ 7, 9 ],   premium: false, name: null },
        germany_PzVI:                   { tiers: [ 7, 9 ],   premium: false, name: null },
        germany_PzVI_Tiger_P:           { tiers: [ 7, 9 ],   premium: false, name: null },
        usa_T29:                        { tiers: [ 7, 9 ],   premium: false, name: null },
        france_AMX_M4_1945:             { tiers: [ 7, 9 ],   premium: false, name: null },
        uk_GB10_Black_Prince:           { tiers: [ 7, 9 ],   premium: false, name: null },
        china_Ch10_IS2:                 { tiers: [ 7, 9 ],   premium: false, name: null },
        ussr_SU100M1:                   { tiers: [ 7, 9 ],   premium: false, name: null },
        ussr_SU_152:                    { tiers: [ 7, 9 ],   premium: false, name: null },
        germany_JagdPanther:            { tiers: [ 7, 9 ],   premium: false, name: null },
        usa_T25_2:                      { tiers: [ 7, 9 ],   premium: false, name: null },
        usa_T25_AT:                     { tiers: [ 7, 9 ],   premium: false, name: null },
        france_AMX_AC_Mle1946:          { tiers: [ 7, 9 ],   premium: false, name: null },
        ussr_Object_212:                { tiers: [ 10, 11 ], premium: false, name: null },
        germany_G_Tiger:                { tiers: [ 10, 11 ], premium: false, name: null },
        usa_M40M43:                     { tiers: [ 10, 11 ], premium: false, name: null },
        france_Lorraine155_51:          { tiers: [ 10, 11 ], premium: false, name: null },

        // level 8
        france_AMX_13_90:               { tiers: [ 9, 12 ],  premium: false, name: null },
        china_Ch17_WZ131_1_WZ132:       { tiers: [ 9, 12 ],  premium: false, name: null },
        ussr_T_44:                      { tiers: [ 8, 10 ],  premium: false, name: null },
        germany_Panther_II:             { tiers: [ 8, 10 ],  premium: false, name: null },
        usa_Pershing:                   { tiers: [ 8, 10 ],  premium: false, name: null },
        usa_T23:                        { tiers: [ 8, 10 ],  premium: false, name: null },
        usa_T69:                        { tiers: [ 8, 10 ],  premium: false, name: null },
        uk_GB23_Centurion:              { tiers: [ 8, 10 ],  premium: false, name: null },
        china_Ch05_T34_2:               { tiers: [ 8, 10 ],  premium: false, name: null },
        ussr_IS_3:                      { tiers: [ 8, 10 ],  premium: false, name: null },
        ussr_KV4:                       { tiers: [ 8, 10 ],  premium: false, name: null },
        germany_Lowe:                   { tiers: [ 8, 10 ],  premium: true,  name: null },
        germany_PzVIB_Tiger_II:         { tiers: [ 8, 10 ],  premium: false, name: null },
        germany_VK4502A:                { tiers: [ 8, 10 ],  premium: false, name: null },
        usa_M6A2E1:                     { tiers: [ 8, 10 ],  premium: true,  name: null },
        usa_T32:                        { tiers: [ 8, 10 ],  premium: false, name: null },
        usa_T34_hvy:                    { tiers: [ 8, 10 ],  premium: true,  name: null },
        france_AMX_50_100:              { tiers: [ 8, 10 ],  premium: false, name: null },
        uk_GB11_Caernarvon:             { tiers: [ 8, 10 ],  premium: false, name: null },
        china_Ch03_WZ_111:              { tiers: [ 8, 10 ],  premium: true,  name: null },
        china_Ch11_110:                 { tiers: [ 8, 10 ],  premium: false, name: null },
        ussr_ISU_152:                   { tiers: [ 8, 10 ],  premium: false, name: null },
        ussr_SU_101:                    { tiers: [ 8, 10 ],  premium: false, name: null },
        germany_Ferdinand:              { tiers: [ 8, 10 ],  premium: false, name: null },
        germany_JagdPantherII:          { tiers: [ 8, 10 ],  premium: false, name: null },
        usa_T28:                        { tiers: [ 8, 10 ],  premium: false, name: null },
        usa_T28_Prototype:              { tiers: [ 8, 10 ],  premium: false, name: null },
        france_AMX_AC_Mle1948:          { tiers: [ 8, 10 ],  premium: false, name: null },
        ussr_Object_261:                { tiers: [ 11, 12 ], premium: false, name: null },
        germany_G_E:                    { tiers: [ 11, 12 ], premium: false, name: null },
        usa_T92:                        { tiers: [ 11, 12 ], premium: false, name: null },
        france_Bat_Chatillon155:        { tiers: [ 11, 12 ], premium: false, name: null },

        // level 9
        ussr_T_54:                      { tiers: [ 9, 11 ],  premium: false, name: null },
        germany_E_50:                   { tiers: [ 9, 11 ],  premium: false, name: null },
        usa_M46_Patton:                 { tiers: [ 9, 11 ],  premium: false, name: null },
        usa_T54E1:                      { tiers: [ 9, 11 ],  premium: false, name: null },
        france_Lorraine40t:             { tiers: [ 9, 11 ],  premium: false, name: null },
        uk_GB24_Centurion_Mk3:          { tiers: [ 9, 11 ],  premium: false, name: null },
        china_Ch18_WZ_120:              { tiers: [ 9, 11 ],  premium: false, name: null },
        ussr_IS8:                       { tiers: [ 9, 11 ],  premium: false, name: null },
        ussr_ST_I:                      { tiers: [ 9, 11 ],  premium: false, name: null },
        germany_E_75:                   { tiers: [ 9, 11 ],  premium: false, name: null },
        germany_VK4502P:                { tiers: [ 9, 11 ],  premium: false, name: null },
        usa_M103:                       { tiers: [ 9, 11 ],  premium: false, name: null },
        france_AMX_50_120:              { tiers: [ 9, 11 ],  premium: false, name: null },
        uk_GB12_Conqueror:              { tiers: [ 9, 11 ],  premium: false, name: null },
        china_Ch12_111_1_2_3:           { tiers: [ 9, 11 ],  premium: false, name: null },
        ussr_Object_704:                { tiers: [ 9, 11 ],  premium: false, name: null },
        ussr_SU122_54:                  { tiers: [ 9, 11 ],  premium: false, name: null },
        germany_JagdTiger:              { tiers: [ 9, 11 ],  premium: false, name: null },
        usa_T30:                        { tiers: [ 9, 11 ],  premium: false, name: null },
        usa_T95:                        { tiers: [ 9, 11 ],  premium: false, name: null },
        france_AMX50_Foch:              { tiers: [ 9, 11 ],  premium: false, name: null },

        // level 10
        ussr_T62A:                      { level: 10, type: "MT",  tiers: [ 10, 12 ], premium: false, name: null },
        germany_E50_Ausf_M:             { level: 10, type: "MT",  tiers: [ 10, 12 ], premium: false, name: null },
        usa_M48A1:                      { level: 10, type: "MT",  tiers: [ 10, 12 ], premium: false, name: null },
        france_Bat_Chatillon25t:        { level: 10, type: "MT",  tiers: [ 10, 12 ], premium: false, name: null },
        uk_GB70_FV4202_105:             { level: 10, type: "MT",  tiers: [ 10, 12 ], premium: false, name: null },
        china_Ch19_121:                 { level: 10, type: "MT",  tiers: [ 10, 12 ], premium: false, name: null },
        ussr_IS_4:                      { level: 10, type: "HT",  tiers: [ 10, 12 ], premium: false, name: null },
        ussr_IS_7:                      { level: 10, type: "HT",  tiers: [ 10, 12 ], premium: false, name: null },
        germany_E_100:                  { level: 10, type: "HT",  tiers: [ 10, 12 ], premium: false, name: null },
        germany_Maus:                   { level: 10, type: "HT",  tiers: [ 10, 12 ], premium: false, name: null },
        usa_T110:                       { level: 10, type: "HT",  tiers: [ 10, 12 ], premium: false, name: null },
        usa_T57_58:                     { level: 10, type: "HT",  tiers: [ 10, 12 ], premium: false, name: null },
        france_F10_AMX_50B:             { level: 10, type: "HT",  tiers: [ 10, 12 ], premium: false, name: null },
        uk_GB13_FV215b:                 { level: 10, type: "HT",  tiers: [ 10, 12 ], premium: false, name: null },
        china_Ch22_113:                 { level: 10, type: "HT",  tiers: [ 10, 12 ], premium: false, name: null },
        ussr_Object263:                 { level: 10, type: "TD",  tiers: [ 10, 12 ], premium: false, name: null },
        ussr_Object268:                 { level: 10, type: "TD",  tiers: [ 10, 12 ], premium: false, name: null },
        germany_JagdPz_E100:            { level: 10, type: "TD",  tiers: [ 10, 12 ], premium: false, name: null },
        usa_T110E3:                     { level: 10, type: "TD",  tiers: [ 10, 12 ], premium: false, name: null },
        usa_T110E4:                     { level: 10, type: "TD",  tiers: [ 10, 12 ], premium: false, name: null },
        france_AMX_50Fosh_155:          { level: 10, type: "TD",  tiers: [ 10, 12 ], premium: false, name: null },

        // non-standard
        usa_T2_lt:                      { level: 2,  type: "LT",  tiers: [ 2, 4 ],   premium: true,  name: null },
        germany_Bison_I:                { level: 2,  type: "SPG", tiers: [ 3, 5 ],   premium: false, name: null },
        ussr_BT_SV:                     { level: 3,  type: "LT",  tiers: [ 3, 4 ],   premium: true,  name: null },
        ussr_M3_Stuart_LL:              { level: 3,  type: "LT",  tiers: [ 3, 4 ],   premium: true,  name: null },
        ussr_T_127:                     { level: 3,  type: "LT",  tiers: [ 3, 4 ],   premium: true,  name: null },
        germany_PzII_J:                 { level: 3,  type: "LT",  tiers: [ 3, 4 ],   premium: true,  name: null },
        ussr_T_50:                      { level: 4,  type: "LT",  tiers: [ 5, 9 ],   premium: false, name: null },
        ussr_Valentine_LL:              { level: 4,  type: "LT",  tiers: [ 4, 4 ],   premium: true,  name: null },
        germany_VK1602:                 { level: 4,  type: "LT",  tiers: [ 5, 9 ],   premium: false, name: null },
        france_AMX40:                   { level: 4,  type: "LT",  tiers: [ 4, 6 ],   premium: false, name: null },
        ussr_A_32:                      { level: 4,  type: "MT",  tiers: [ 4, 5 ],   premium: true,  name: null },
        germany_B_1bis_captured:        { level: 4,  type: "HT",  tiers: [ 4, 4 ],   premium: true,  name: null },
        france__105_leFH18B2:           { level: 4,  type: "SPG", tiers: [ 5, 7 ],   premium: true,  name: null },
        france_ELC_AMX:                 { level: 5,  type: "LT",  tiers: [ 6, 9 ],   premium: false, name: null },
        ussr_Matilda_II_LL:             { level: 5,  type: "MT",  tiers: [ 5, 6 ],   premium: true,  name: null },
        germany_PzIV_Hydro:             { level: 5,  type: "MT",  tiers: [ 5, 6 ],   premium: true,  name: null },
        usa_M4A2E4:                     { level: 5,  type: "MT",  tiers: [ 5, 6 ],   premium: true,  name: null },
        uk_GB68_Matilda_Black_Prince:   { level: 5,  type: "MT",  tiers: [ 5, 6 ],   premium: true,  name: null },
        ussr_Churchill_LL:              { level: 5,  type: "HT",  tiers: [ 5, 6 ],   premium: true,  name: null },
        ussr_KV_220:                    { level: 5,  type: "HT",  tiers: [ 5, 6 ],   premium: true,  name: null },
        ussr_KV_220_action:             { level: 5,  type: "HT",  tiers: [ 5, 6 ],   premium: true,  name: null },
        usa_T14:                        { level: 5,  type: "HT",  tiers: [ 5, 6 ],   premium: true,  name: null },
        germany_PzV_PzIV:               { level: 6,  type: "MT",  tiers: [ 6, 7 ],   premium: true,  name: null },
        germany_PzV_PzIV_ausf_Alfa:     { level: 6,  type: "MT",  tiers: [ 6, 7 ],   premium: true,  name: null },
        germany_PzIV_schmalturm:        { level: 6,  type: "MT",  tiers: [ 6, 7 ],   premium: true,  name: null },
        uk_GB63_TOG_II:                 { level: 6,  type: "HT",  tiers: [ 6, 7 ],   premium: true,  name: null },
        ussr_SU100Y:                    { level: 6,  type: "TD",  tiers: [ 6, 7 ],   premium: true,  name: null },
        germany_Panther_M10:            { level: 7,  type: "MT",  tiers: [ 7, 8 ],   premium: true,  name: null },
        ussr_SU122_44:                  { level: 7,  type: "TD",  tiers: [ 7, 8 ],   premium: true,  name: null },
        uk_GB71_AT_15A:                 { level: 7,  type: "TD",  tiers: [ 7, 8 ],   premium: true,  name: null },
        usa_T26_E4_SuperPershing:       { level: 8,  type: "MT",  tiers: [ 8, 9 ],   premium: true,  name: null },
        china_Ch01_Type59:              { level: 8,  type: "MT",  tiers: [ 8, 9 ],   premium: true,  name: null },
        china_Ch01_Type59_gold:         { level: 8,  type: "MT",  tiers: [ 8, 9 ],   premium: true,  name: null },
        ussr_KV_5:                      { level: 8,  type: "HT",  tiers: [ 8, 9 ],   premium: true,  name: null },
        ussr_Object252:                 { level: 8,  type: "HT",  tiers: [ 8, 9 ],   premium: true,  name: null },
        france_FCM_50t:                 { level: 8,  type: "HT",  tiers: [ 8, 9 ],   premium: true,  name: null },
        germany_JagdTiger_SdKfz_185:    { level: 8,  type: "TD",  tiers: [ 8, 9 ],   premium: true,  name: null },

        // DO NOT REMOVE
        unknown:                        { level: 0,  type: "",  tiers: [ 0, 0 ],   premium: false, name: null }
    }
}
