//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleBankParser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\work\\wot-xvm\\src\\xvm\\src\\com\\xvm\\VehicleInfoData2.as")]
        public string EXPORT_FILEPATH {
            get {
                return ((string)(this["EXPORT_FILEPATH"]));
            }
            set {
                this["EXPORT_FILEPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("res\\scripts\\item_defs\\vehicles\\")]
        public string VEHICLE_DIR_PATH {
            get {
                return ((string)(this["VEHICLE_DIR_PATH"]));
            }
            set {
                this["VEHICLE_DIR_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\work\\games\\WoT\\")]
        public string GAME_PATH {
            get {
                return ((string)(this["GAME_PATH"]));
            }
            set {
                this["GAME_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\work\\wot-xvm\\release\\res\\VehicleInfo.json")]
        public string EXPORT_FILEPATH_JSON {
            get {
                return ((string)(this["EXPORT_FILEPATH_JSON"]));
            }
            set {
                this["EXPORT_FILEPATH_JSON"] = value;
            }
        }
    }
}
