/**
 * This file is automatically generated by VehicleBankParser program.
 * Data extracted from WoT version 0.7.5
 */

class wot.VehicleMarkersManager.components.TurretStatusCSV
{
    /**
     * Vehicles in list has two turret modules.
     * Format:
     * vehicel name, stock max hp, turret status
     * Turret status: 2 - unable to mount top gun to stock turret, 1 - able
     */
    public var:String = "
        a-20, 290, 2
        amx_m4_1945, 1100, 2
        amx40, 280, 2
        arl_44, 780, 2
        b1, 380, 2
        bdr_g1b, 600, 2
        bt-2, 140, 2
        bt-7, 185, 2
        d1, 155, 2
        d2, 220, 2
        e-50, 1650, 2
        e-75, 1820, 2
        is, 1130, 2
        is-3, 1450, 1
        is8, 1700, 1
        kv, 560, 1
        kv1, 590, 2
        kv-13, 1020, 2
        kv-1s, 760, 2
        kv2, 810, 1
        kv-3, 1300, 2
        kv4, 1600, 1
        ltraktor, 110, 2
        m10_wolverine, 340, 2
        m103, 1750, 2
        m18_hellcat, 550, 2
        m2_lt, 140, 2
        m2_med, 180, 2
        m24_chaffee, 530, 2
        m3_stuart, 220, 2
        m36_slagger, 560, 1
        m4_sherman, 400, 2
        m46_patton, 1600, 2
        m4a3e8_sherman, 720, 2
        m5_stuart, 290, 2
        m6, 840, 2
        m7_med, 380, 2
        m8a1, 250, 2
        ms-1, 90, 2
        panther_ii, 1350, 2
        pershing, 1350, 2
        pz35t, 150, 1
        pz38_na, 300, 2
        pz38t, 200, 2
        pzii, 145, 2
        pzii_luchs, 190, 2
        pziii, 310, 2
        pziii_a, 200, 2
        pziii_iv, 380, 1
        pziv, 390, 2
        pzv, 1200, 2
        pzvi, 1350, 2
        pzvi_tiger_p, 1350, 1
        pzvib_tiger_ii, 1500, 2
        renaultft, 105, 2
        sherman_jumbo, 730, 2
        st_i, 1800, 2
        t_50_2, 500, 2
        t1_cunningham, 105, 2
        t1_hvy, 600, 2
        t150, 830, 2
        t2_med, 150, 2
        t20, 1000, 2
        t23, 1310, 1
        t25_2, 800, 2
        t-26, 150, 1
        t-28, 320, 1
        t29, 1150, 2
        t32, 1400, 2
        t-34, 400, 2
        t-34-85, 670, 2
        t-43, 1000, 2
        t-44, 1200, 2
        t-46, 220, 2
        t49, 340, 2
        t-54, 1550, 2
        vk2801, 560, 2
        vk3001h, 670, 2
        vk3001p, 610, 2
        vk3002db, 1180, 2
        vk3601h, 760, 2
        vk4502a, 1470, 2
        vk4502p, 1850, 2
    ";
}
