using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

static class Export
{
    //private const string EXPORT_FILEPATH = @"C:\temp\TurretStatusCSV.as";
    private const string EXPORT_FILEPATH = @"D:\xvm\src\xvm\src\wot\VehicleMarkersManager\components\TurretStatusCSV.as";

    public static void CSV(List<Vehicle> vehList)
    {
        StreamWriter file = new System.IO.StreamWriter(EXPORT_FILEPATH);

        writeHeader(file);
        writeCsv(file, vehList);
        writeFooter(file);
        
        file.Close();
    }

    private static void writeHeader(StreamWriter file)
    {
        file.WriteLine(@"/**");
        file.WriteLine(" * This file is automatically generated by VehicleBankParser program.");
        file.WriteLine(" * Data extracted from WoT version 0.7.5");
        file.WriteLine(@" */");
        file.WriteLine("");
        file.WriteLine("class wot.VehicleMarkersManager.components.TurretStatusCSV");
        file.WriteLine("{");
        file.WriteLine(@"    /**");
        file.WriteLine("     * Vehicles in list has two turret modules.");
        file.WriteLine("     * Format:");
        file.WriteLine("     * vehicel name, stock max hp, turret status");
        file.WriteLine("     * Turret status: 2 - unable to mount top gun to stock turret, 1 - able");
        file.WriteLine(@"     */");
        file.WriteLine("    public var:String = \"");
    }

    private static void writeCsv(StreamWriter file, List<Vehicle> vehList)
    {
        foreach (Vehicle veh in vehList)
            file.WriteLine("        " + veh.name + ", " + veh.hpstock + ", " + veh.status);
    }

    private static void writeFooter(StreamWriter file)
    {
        file.WriteLine("    \";");
        file.WriteLine("}");
    }
}

