#!/usr/bin/env python2
# -*- coding: utf-8 -*-

""" This is XVM FUSE driver implementation with additional features
    required for XVM mod.

    XVM is popular mod for 'Worls of Tanks' MMO game.
    Original mod is located at http://code.google.com/p/wot-xvm/

    This code is distributed under GNU GPL v3 public license.
"""

import fuse
import os, sys, stat, errno
import threading, time
import logging, traceback
import re, base64, json
from fuse import Fuse
from datetime import datetime
from random import randint
from urllib2 import urlopen
from xml.dom import minidom

""" Global constants and variables section.
"""

# Based on XVM 3.5.0, SVN rev. 1604
# Last change of xvm-stat: SVN rev. 1604

XVMFS_VERSION = '0.3.0'
fuse.fuse_python_api = (0, 2)

# Logging configuration.
# Log level is set to logging.INFO by default.
# Use mount option 'debug' to get more detailed logs.
# The log files are created in the current directory by default.
# Use '-o log_dir=...' option to override it.
# Example:
# $ ./xvmfs -o debug -o log_dir=/tmp/xvm res_mods/.stat
LOG_DIR = '.'
XVM_LOG = 'xvmfs.log'
XVM_STAT_LOG = 'xvmfs-stat.log'
Log = None
LogStat = None

# Original XVM config file holds the list of available XVM proxies
DEFAULT_XVM_CFG = 'xvm-stat.exe.config'
DEFAULT_WOT_CFG = 'WOTLauncher.cfg'

# Required only if the game is installed on NTFS partition because of
# NTFS filename limit to 255 chars.
WINE_GAME_DIR = 'C:\\Games\\World_of_Tanks'

# Components of virtual FS
README_PATH = '/README'
README_DATA = """This is README virtual file content.
This file indicates that XVM filesystem is mounted into current folder.

The XvmFS can be unmounted by issuing following command:
 $ fusermount -u <mount point>
where <mount point> is (you'll never guess) the path to the folder
which contains this file.
"""
DIR_ITEMS = ['.', '..', README_PATH[1:]]

# All XVM commands begins with following prefix.
BEGIN_CMD = '/@'

# Used to choose some fast proxies from available proxy pool
PING_THRESHOLD = 500

lock = threading.RLock()
# remove lockIngame
lockNetwork = threading.RLock()
lockResults = threading.RLock()

EMPTY_RESULT = '{"status":"EMPTY"}'
BAD_REQUEST_RESULT = '{"status":"BAD_REQUEST"}'
PUBLIC_TOKEN = 'linux'

""" Classes definition section.
"""
class XvmStat(fuse.Stat):
    def __init__(self):
        self.st_mode = 0
        self.st_ino = 0
        self.st_dev = 0
        self.st_nlink = 0
        self.st_uid = os.getuid()
        self.st_gid = os.getgid()
        self.st_size = 0
        self.st_atime = 0
        self.st_mtime = 0
        self.st_ctime = 0

class XvmFS(Fuse):
    # FUSE interface implementation

    def __init__(self, *args, **kw):
        self._start_time_unix = time.mktime(datetime.now().timetuple())
        self.result = ''
        self.command = None
        self.logString = None
        self.logLength = 0
        self.vars = {}
        self.results = []
        self.xvm_cfg = DEFAULT_XVM_CFG
        self.wot_cfg = DEFAULT_WOT_CFG
        self.game_dir = WINE_GAME_DIR
        self.cache = {}
        self.infocache = {}
        self.modInfo = None
        self.debug = False
        self.log_dir = LOG_DIR
        self.timeout = 10000

        Fuse.__init__(self, *args, **kw)

    def init(self):
        try:
            Log.info('')
            Log.info("XvmFS %s is started." % XVMFS_VERSION)

            self.check_params()
            self.version = self.GetVersion()
            self.proxies = self.GetProxyAddresses()

        except Exception, ex:
            Log.debug('XvmFS init exception:\n' + traceback.format_exc(ex))
            raise

    def fsinit(self):
        Log.debug('xvm_cfg is ' + str(self.xvm_cfg))
        Log.debug('wot_cfg is ' + str(self.wot_cfg))
        Log.debug('game_dir is ' + str(self.game_dir))

    def getattr(self, path):
        st = XvmStat()
        st.st_ctime = self._start_time_unix

        if path == '/':
            st.st_mode = stat.S_IFDIR | 0755
            st.st_nlink = 2
        elif path == README_PATH:
            st.st_mode = stat.S_IFREG | 0444
            st.st_nlink = 1
            st.st_size = len(README_DATA)
        elif path[:2] == BEGIN_CMD:
            self.xvm_exec_cmd(path[1:].upper())
            st.st_mode = stat.S_IFREG | 0444
            st.st_nlink = 1
            st.st_size = len(self.result) if self.result is not None else 0
            st.st_mtime = time.mktime(datetime.now().timetuple())
        else:
            return -errno.ENOENT

        return st

    def readdir(self, path, offset):
        for d in DIR_ITEMS:
            yield fuse.Direntry(d)

    def open(self, path, flags):
        if path != README_PATH and path[:2] != BEGIN_CMD:
            return -errno.ENOENT

        accmode = os.O_RDONLY | os.O_WRONLY | os.O_RDWR
        if (flags & accmode) != os.O_RDONLY:
            return -errno.EACCES

    def read(self, path, size, offset):
        if path == README_PATH:
            data = README_DATA
        elif path[:2] == BEGIN_CMD:
            data = self.result
        else:
            return -errno.ENOENT

        if data is None:
            return ''

        slen = len(data)
        if offset < slen:
            if offset + size > slen:
                size = slen - offset
            buf = data[offset:offset+size]
        else:
            buf = ''

        return buf

    """ XVM command handling
    """

    def xvm_exec_cmd(self, command):
        if command == self.command:
            return
        with lock:
            self.command = command
            self.result = ''
            cmd = command.split(' ', 1)
            command = cmd[0]
            parameters = cmd[1] if len(cmd) > 1 else ''

            if command == '':
                self.result = BAD_REQUEST_RESULT
                return

            if command not in ['@LOG', '@LOGSTAT', '@SET', '@ADD']:
                Log.info("=> %s %s" % (command, parameters))

            try:
                if command == '@LOG':
                    self.ProcessLog(parameters, Log)
                elif command == '@LOGSTAT':
                    self.ProcessLog(parameters, LogStat)

                elif command in ['@SET', '@ADD']:
                    value = CollectParts(parameters)
                    if value:
                        Log.debug('%s %s' % (command, value))
                        if command == '@SET':
                            with lockResults:
                                self.results.append(dict(result=None, thread=None, players=[]))
                        self.AddPendingPlayers(value)
                    self.result = '{"resultId":%d}' % (len(self.results) - 1)

                elif command == '@VAR':
                    v = parameters.split('=', 1)
                    if len(v) < 2:
                        raise Exception('Bad variable received: ' + parameters)
                    Log.info("SET VAR: " + parameters)
                    self.vars[v[0].strip()] = v[1]

                elif command == '@GET_VERSION':
                    result = [self.version, self.game_dir]
                    result = result + ["%s=%s" % (key, value)
                            for (key, value) in self.vars.items()]
                    self.result = '\n'.join(result)
                    Log.debug('result: ' + str(self.result))

                elif command == '@GET_PLAYERS':
                    if len(self.results) <= 0:
                        raise Exception('No last result: -1')
                    with lockResults:
                        if self.results[-1]['players'] is None:
                            raise Exception('No players: %d' + len(self.results))
                        self.result = json.dumps(self.results[-1]['players'])
                    Log.debug('result: ' + str(self.result))

                elif command == '@GET_ASYNC':
                    def target(resultId, arg):
                        with lockNetwork:
                            with lockResults:
                                r = self.results[resultId]
                            res = self.GetStat(r)
                            with lockResults:
                                if not res:
                                    res = '{"status":"ERROR","error":"no result: %d"}' % (resultId)
                                self.results[resultId]['result'] = res
                                self.results[resultId]['thread'] = None
                    self.result = self.AsyncWrapper(parameters, target)
                    Log.debug('result: ' + str(self.result))

                elif command == '@INFO_ASYNC':
                    def target(resultId, arg):
                        with lockNetwork:
                            res = self.GetInfo(r)
                            with lockResults:
                                if not res:
                                    res = '{"status":"ERROR","error":"no result: %d"}' % (resultId)
                                self.results[resultId]['result'] = res
                                self.results[resultId]['thread'] = None
                    self.result = self.AsyncWrapper(parameters, target)
                    Log.debug('result: ' + str(self.result))
            except Exception, ex:
                Log.error("Exception during %s: %s" % (str(command), str(ex)))
                Log.debug('\n' + traceback.format_exc(ex))

    def AsyncWrapper(self, parameters, target):
        if parameters in ['', None]:
            raise Exception('Empty resultId')

        p = re.split('\s+', parameters, 2)
        try:
            resultId = int(p[0])
            if not -1 <= resultId < len(self.results):
                raise Exception()
        except:
            raise Exception('Invalid resultId: ' + p[0])

        with lockResults:
            if resultId == -1:
                self.results.append(dict(result=None, thread=None))
                resultId = len(self.results) - 1
            res = self.results[resultId]
            if res['result']:
                return res['result']
            if res['thread'] is None:
                args = p[2] if len(p) > 2 else ''
                t = threading.Thread(target=target, args=(resultId, args))
                res['thread'] = t
                t.start()

            return '{"status":"NOT_READY","resultId":%d}' % (resultId)

    """ Network operations
    """

    def GetVersion(self):
        Log.debug('GetVersion: current dir is ' + os.path.abspath('.'))
        wotVersion = 'RU'

        try:
            xmldoc = minidom.parse(self.wot_cfg)
            xnl = xmldoc.documentElement.getElementsByTagName('patch_info_urls')[0].childNodes

            for url in [x.firstChild.wholeText for x in xnl
                    if x.nodeType == x.ELEMENT_NODE
                        and x.firstChild.nodeType == x.TEXT_NODE]:

                if (url.rfind('http://update.wot.ru.wargaming.net') > -1
                        or url.rfind('http://update.worldoftanks.ru') > -1):
                    wotVersion = 'RU'
                elif url.rfind('http://update.worldoftanks.com') > -1:
                    wotVersion = 'US'
                elif url.rfind('http://update.worldoftanks.eu') > -1:
                    wotVersion = 'EU'
                elif url.rfind('http://update.worldoftanks.cn') > -1:
                    wotVersion = 'CN'
                elif url.rfind('http://update.worldoftanks-sea.com') > -1:
                    wotVersion = 'SEA'
                elif url.rfind('http://update.worldoftanks.vn') > -1:
                    wotVersion = 'VTC'
                elif url.rfind('http://update.worldoftanks.kr') > -1:
                    wotVersion = 'KR'
                elif url.rfind('http://update-ct.wargaming.net/') > -1:
                    wotVersion = 'CT'

        except Exception, ex:
            Log.debug("GetVersion exception: %s\n%s" % (str(ex),
                    traceback.format_exc(ex)))
            raise Exception('Failed to parse config file: ' + str(ex))

        wotVersion = wotVersion.upper()
        Log.info('GetVersion: server version = ' + wotVersion)
        return wotVersion

    def GetProxyAddresses(self):
        """ Actually, this method is (and should be) used to parse
            XVM config file.
        """
        if not os.path.isfile(self.xvm_cfg):
            raise Exception('XVM config file was not found.')

        # Retrieve raw proxy list from XVM config file
        allProxies = []
        try:
            xmldoc = minidom.parse(self.xvm_cfg)
            xs = [x for x in xmldoc.getElementsByTagName('setting')
                    if x.getAttribute('name') == 'ProxyServers'][0]
            xv = xs.getElementsByTagName('value')[0]
            allProxies = [x.firstChild.wholeText
                    for x in xv.getElementsByTagName('string')
                        if x.nodeType == x.ELEMENT_NODE
                            and x.firstChild.nodeType == x.TEXT_NODE]

            # Also read timeout value from the same config file.
            xs = [x for x in xmldoc.getElementsByTagName('setting')
                    if x.getAttribute('name') == 'Timeout'][0]
            timeout = xs.getElementsByTagName('value')[0].firstChild.wholeText
            self.timeout = int(timeout)

        except Exception, ex:
            Log.error('Exception during XML parsing: ' + str(ex))
            Log.debug("\n" + traceback.format_exc(ex))
            return []

        # Find suitable proxies for current region
        ps = []
        for server in allProxies:
            s = [x for x in re.split(' |\t', server) if len(x) > 0]
            if len(s) >= 2 and s[0].upper() == self.version:
               ps.append(s[1])

            if len(s) >= 2 and self.version == 'CT' and s[0].upper == 'RU':
                ps.append(s[1])

        if len(ps) <= 0:
            raise Exception("Cannot find proxy server for '%s' in config"
                    % self.version)

        # Measure proxy latency
        proxyUrls = {}
        for addr in ps:
            tempUrl = base64.b64decode(addr)
            tmpTime = None

            try:
                data, tmpTime = self.loadUrl(tempUrl, 'test', True)
            except:
                Log.info("Exception: " + str(ex))

            proxyUrls[tempUrl] = tmpTime

        # Select a bunch of fastest proxies found
        minTime = min(proxyUrls.values())
        proxyUrl = [x for x in proxyUrls
                if proxyUrls[x] - minTime < PING_THRESHOLD]

        Log.debug('Acceptable proxies = ' + str(proxyUrl))

        """ However, novadays only 3 XVM proxy servers exist, and 2 of them
            are exclusively for China. So, the other part of the world uses
            explicitly one proxy server.

            The calculations above will be handy in future.
            Maybe.
        """

        return proxyUrl

    def loadUrl(self, url, members, test=False):
        if not test:
            Log.info('HTTP: ' + str(members))

        url = url.replace('%1', members).replace('%2', PUBLIC_TOKEN)
        Log.debug('loadUrl: ' + url )

        duration = None
        responseFromServer = ''
        startTime = datetime.now()
        response = None

        try:
            response = urlopen(url=url, timeout=self.timeout / 1000)
            code = response.getcode()

            if code in [200, 202]:
                # 200 OK, 202 Accepted
                responseFromServer = response.read()

        except Exception, ex:
            Log.error('loadUrl failed: ' + str(ex))
        finally:
            if response != None:
                response.close()

        elapsed = datetime.now() - startTime
        msec = elapsed.seconds * 1000 + elapsed.microseconds / 1000
        Log.info("  Time: %d ms, Size: %d bytes" % (msec, len(responseFromServer)))
        Log.debug('responseFromServer: ' + responseFromServer)

        if not responseFromServer.lower().startswith('onexception'):
            duration = msec

        return responseFromServer, duration

    """ Stat operations
    """

    def AddPendingPlayers(self, value):
        pd = json.loads(value.replace('\n', '\\n'))
        found = next((True for x in self.results[-1]['players']
                if x['id'] == pd['id']), False)
        if found:
            return
        n = re.split('[\[\] ]+', pd['n'])
        pd['_label'] = n[0].upper()
        pd['_clan'] = n[1].upper() if len(n) > 1 else ''
        self.results[-1]['players'].append(pd)

    def GetStat(self, req):
        self.PrepareStat(req)
        res = dict(players=[], info=dict(xvm=self.modInfo))

        for pd in req['players']:
            cacheKey = "%d=%s" % (pd['id'], pd['v'])

            if self.cache.has_key(cacheKey):
                item = self.cache[cacheKey]
                item['name'] = pd['_label']
                res['players'].append(item)

        return json.dumps(res)

    def PrepareStat(self, req):
        requestList = []

        for pd in req['players']:
            cacheKey = "%(id)d=%(v)s" % pd

            if self.cache.has_key(cacheKey):
                continue

            if pd['v'] in [None, '']:
                requestList.append(str(pd['id']))
            else:
                requestList.append("%d=%s%s" % (pd['id'], pd['v'],
                        '=1' if pd['s'] == 1 else ''))

        updateRequest = ','.join(requestList)
        if len(updateRequest) <= 0:
            return

        if self.proxies is None or len(self.proxies) <= 0:
            Log.warning('Cannot read statistics: no suitable proxy was found.')
            return

        try:
            updateRequest = updateRequest.replace('?', '%3F')
            proxy = self.proxies[randint(0, len(self.proxies) - 1)]
            responseFromServer, duration = self.loadUrl(proxy, updateRequest)

            if len(responseFromServer) <= 0:
                Log.warning('Empty response or parsing error')
                return

            try:
                data = json.loads(responseFromServer)
            except ValueError:
                try:
                    data = json.loads(responseFromServer.replace('\n', '\\n'))
                except ValueError:
                    try:
                        data = json.loads(responseFromServer.replace('\\n', '\\\\n'))
                    except ValueError:
                        Log.error('Failed to parse stat data')
                        return

            if not data.has_key('players'):
                Log.warning('Stat request failed: ' + str(responseFromServer))
                return

            info = data['info'][self.version] if data.has_key('info') else None
            res = dict(players=data['players'], info=None)

            if info is not None:
                self.modInfo = info

            stat_v_stub = dict(b=0, d=0, f=0, l=0, s=0, w=0, name='')

            for stat in data['players']:
                if not stat.has_key('name') or len(stat['name']) <= 0:
                    continue
                if not stat.has_key('v'):
                    stat['v'] = stat_v_stub

                """ Convert tree-ish data structure to flat, and modify key names.
                    The same job does 'JsonDataToResponse' method in original XVM.
                    Item conversion format is: (JSON key, XVM key, default value)
                """
                keys1 = (('id', 'id', 0)
                    , ('name', 'name', '')
                    , ('vname', 'vn', '')
                    , ('battles', 'b', 0)
                    , ('wins', 'w', 0)
                    , ('eff', 'e', 0)
                    , ('spo', 'spo', 0)
                    , ('hip', 'hip', 0)
                    , ('cap', 'cap', 0)
                    , ('dmg', 'dmg', 0)
                    , ('frg', 'frg', 0)
                    , ('def', 'def', 0)
                    , ('lvl', 'avglvl', 0)
                    , ('wn', 'wn', 0)
                    , ('twr', 'twr', 0)
                )

                keys2 = (('b', 'tb', 0)
                    , ('w', 'tw', 0)
                    , ('l', 'tl', 0)
                    , ('s', 'ts', 0)
                    , ('d', 'td', 0)
                    , ('f', 'tf', 0)
                )

                stat = dict([(y, stat[x]) if stat.has_key(x) else (y, z)
                                for (x,y,z) in keys1]
                    + [(y, stat['v'][x]) if stat['v'].has_key(x) else (y, z)
                                for (x,y,z) in keys2])

                cacheKey = "%d=%s" % (stat['id'], stat['vn'] or '')
                self.cache[cacheKey] = stat

                pd = next((x for x in req['players'] if x['id'] == stat['id']), None)
                if pd is not None:
                    stat['name'] = pd['_label']
                    stat['vn'] = pd['v']
                    stat['clan'] = pd['_clan']

            for pd in req['players']:
                cacheKey = "%(id)d=%(v)s" % pd
                if self.cache.has_key(cacheKey):
                    continue

                Log.debug("Player %(id)s %(v)s %(n)s not in Database" % pd)

                self.cache[cacheKey] = dict(
                        id=pd['id']
                        , vn=pd['v']
                        , name=pd['_label']
                        , clan=pd['_clan']
                )

        except Exception, ex:
            Log.error('PrepareStat exception: ' + str(ex))
            Log.debug("\n" + traceback.format_exc(ex))

    def GetInfo(self, req):
        if self.proxies is None or len(self.proxies) <= 0:
            Log.warning('Unable to query user info: no proxy found.')
            return '{"status":"ERROR","error":"NO_DATA"}'

        try:
            s = req.decode('hex')
        except:
            Log.error("Error decoding @INFO string: " + req)
            Log.debug(traceback.format_exc())
            return '{"status":"ERROR","error":"EXCEPTION"}'

        sa = s.split(',')
        if len(sa) > 1:
            s = sa[1] + '/' + sa[0]

        key = "@INFO/" + s
        if self.infocache.has_key(key):
            return self.infocache[key]

        request = "INFO/" + s.replace('?', '%3F')
        proxy = self.proxies[randint(0, len(self.proxies) - 1)]

        try:
            response, duration = self.loadUrl(proxy, request)
        except:
            Log.error('User info query failed.')
            Log.debug(traceback.format_exc())
            return '{"status":"ERROR","error":"EXCEPTION"}'

        if len(response) <= 0:
            Log.error('Empty response or parsing error')
            return '{"status":"ERROR","error":"NO_DATA"}'

        self.infocache[key] = response
        return response

    """ Log processing
    """
    def ProcessLog(self, parameters, logger):
        value = CollectParts(parameters)
        if not value:
            return
        logger.info(value)

    """ Compatibility support
    """

    def check_params(self):
        """Validate XvmFS properties after arguments were parsed"""
        wot_cfg = locate_file(self.wot_cfg)
        xvm_cfg = locate_file(self.xvm_cfg)

        if wot_cfg is None:
            raise Exception("WoT config file '%s' was not found." % self.wot_cfg)
        elif xvm_cfg is None:
            raise Exception("XVM config file '%s' was not found." % self.xvm_cfg)

        self.wot_cfg = wot_cfg
        self.xvm_cfg = xvm_cfg


""" Entry point
"""
def main():
    server = XvmFS(version="%prog " + fuse.__version__,
            usage=Fuse.fusage,
            dash_s_do='setsingle')

    server.parser.add_option(mountopt='xvm_cfg', metavar='FILE',
            help="XVM proxy config file. Default is '%s'" % DEFAULT_XVM_CFG,
            default=DEFAULT_XVM_CFG)

    server.parser.add_option(mountopt='wot_cfg', metavar='FILE',
            help="WoT Launcher config file. Default is '%s'" % DEFAULT_WOT_CFG,
            default=DEFAULT_WOT_CFG)

    server.parser.add_option(mountopt='game_dir', metavar='DIR',
            help='(Obsolete) The path to the game folder as it is displayed'
                + " into Wine. Default is '%s'" % WINE_GAME_DIR,
            default=WINE_GAME_DIR)

    server.parser.add_option(mountopt='log_dir', metavar='DIR', default=LOG_DIR,
            help="Directory for log files. Default is current directory.")

    server.parser.add_option(mountopt='debug', action='store_true',
            help='Enable detailed logging')

    server.parse(values=server, errex=1)

    if server.fuse_args.mount_expected():
        if len(sys.argv) <= 1:
            print >> sys.stderr, "xvmfs: missing mountpoint parameter." + \
                    "\nSee `xvmfs -h' for usage"
            sys.exit(1)

        configureLoggers(server.log_dir,
                logging.DEBUG if server.debug else logging.INFO)
        server.init()

    server.main()

def configureLoggers(logDir, level):
    """Create and customize logger objects"""
    global Log, LogStat

    if not os.path.isfile(logDir) and not os.path.isdir(logDir):
        os.makedirs(logDir)

    formatter = logging.Formatter("%(asctime)s %(levelname)-7s: %(message)s")
    handler = logging.FileHandler(os.path.join(logDir, XVM_LOG), mode='w')
    handler.setFormatter(formatter)

    Log = logging.getLogger('XVM')
    Log.setLevel(level)
    Log.addHandler(handler)

    handler = logging.FileHandler(os.path.join(logDir, XVM_STAT_LOG), mode='w')
    handler.setFormatter(formatter)

    LogStat = logging.getLogger('XVM-STAT')
    LogStat.setLevel(level)
    LogStat.addHandler(handler)

def locate_file(filename):
    """Treat config file names in case-insensitive way"""

    if filename is None or os.path.isfile(filename):
        return filename

    fpath = os.path.abspath(filename)
    fdir, fname = os.path.split(fpath)

    if os.path.isfile(fpath):
        return fpath

    if not os.path.isdir(fdir):
        return None

    fname = fname.lower()
    found = next((x for x in os.listdir(fdir) if x.lower() == fname), None)

    return found

class Parts:
    """    Join together parts of a message and decode it.
    Usage example:
        p = Parts()
        p.SetPart(0,'6c6f72656d2069707')
        p.SetPart(1,'3756d20646f6c6f72207369')
        p.SetPart(2,'7420616d6574')
        p.length = 52
        p.IsComplete()
        print p.value
    The output should be 'lorem ipsum dolor sit amet'
    """
    def __init__(self):
        self.value = None
        self.length = -1
        self.parts = []

    def IsComplete(self):
        if self.value is not None:
            return True
        if None in self.parts:
            return False

        v = ''.join(self.parts)
        self.value = v.decode('hex') if len(v) == self.length else None
        return self.value != None

    def SetPart(self, id, value):
        if len(self.parts) <= id:
            self.parts.extend((id - len(self.parts) + 1) * [None])
        self.parts[id] = value

parts = {}
def CollectParts(parameters):
    param_list = parameters.split(',', 2)
    if len(param_list) != 3:
        Log.error('Malformed parameters: ' + str(parameters))
        return None

    (cmdId, partId, params) = param_list
    try:
        partId = int(partId)
    except ValueError, ve:
        Log.error(str(ve))
        return None
    if cmdId[0] == '_':
        Log.warning('Unknown SWF sandbox ' + cmdId)
    if not parts.has_key(cmdId):
        parts[cmdId] = Parts()

    part = parts[cmdId]
    if partId == 0:
        try:
            (length, params) = params.split(',', 1)
            part.length = int(length, 16)
        except ValueError, ve:
            Log.error(str(ve))
            return None
    part.SetPart(partId, params)
    if not part.IsComplete():
        return None

    del parts[cmdId]
    return part.value

if __name__ == '__main__':
    main()

