using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using VehicleBankParser.Properties;

static class Export
{
    /**
     * Make actionscript 2 code file with predefined array of obtained name\hp\turret data.
     */
    public static void generateAS2code(List<Vehicle> vehList)
    {
        StreamWriter file = new StreamWriter(Settings.Default.EXPORT_FILEPATH, false, Encoding.UTF8);

        //StreamWriter file = new StreamWriter(EXPORT_FILEPATH);

        writeHeader(file);
        writeLines(file, vehList);
        writeFooter(file);

        file.Close();
    }

    private static void writeHeader(StreamWriter file)
    {
        file.WriteLine(
@"/**
* This file is automatically generated by VehicleBankParser program.
* Data extracted from WoT version 0.8.0
*/

class wot.utils.VehicleInfoData2
{
    /**
    * Vehicles in list has two turret modules.
    * Format:
    * vehicel name, stock max hp, turret status
    * Turret status: 2 - unable to mount top gun to stock turret, 1 - able
    */

    public static var data:Object = {
        //vname: { hpstock: #, hptop: #, turretstatus: # }");
    }

    private static void writeLines(StreamWriter file, List<Vehicle> vehList)
    {
        foreach (Vehicle veh in vehList)
        {
            file.WriteLine("        " + veh.name.Replace("-", "_").ToLower() +
                ": { hpstock: " + veh.hpstock + 
                ", hptop: " + veh.hptop + 
                ", turretstatus: " + veh.status + "},");
        }
    }

    private static void writeFooter(StreamWriter file)
    {
file.WriteLine(@"
      __end__: null
    }
}
    ");
    }
}
