using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using VehicleBankParser.Properties;

static class Export
{
    /**
     * Make actionscript 2 code file with predefined array of obtained name\hp\turret data.
     */
    public static void generateAS2code(List<Vehicle> vehList)
    {
        StreamWriter file = new StreamWriter(Settings.Default.EXPORT_FILEPATH, false, Encoding.UTF8);

        //StreamWriter file = new StreamWriter(EXPORT_FILEPATH);

        writeHeader(file);
        writeCsv(file, vehList);
        writeFooter(file);

        file.Close();
    }

    private static void writeHeader(StreamWriter file)
    {
        file.WriteLine(
@"/**
* This file is automatically generated by VehicleBankParser program.
* Data extracted from WoT version 0.8.0
*/

class wot.utils.VehicleInfoData2
{
    /**
    * Vehicles in list has two turret modules.
    * Format:
    * vehicel name, stock max hp, turret status
    * Turret status: 2 - unable to mount top gun to stock turret, 1 - able
    */

    private static var db:Array;

    public static function getDb():Array
    {
        if(db == null)
        {
            db = [];
            // [ hpstock, hptop, turretstatus ]");
    }

    private static void writeCsv(StreamWriter file, List<Vehicle> vehList)
    {
        foreach (Vehicle veh in vehList)
            file.WriteLine("            db[\"" + veh.name + "\"] = [" + veh.hpstock + ", " + veh.hptop + ", " + veh.status + "];");
        //         = new Array()

    }

    private static void writeFooter(StreamWriter file)
    {
file.WriteLine(@"
        }
        return db;
    }
}
    ");
    }
}
