/**
* This file is automatically generated by VehicleBankParser program.
* Data extracted from WoT version 0.8.0
*/
intrinsic class com.xvm.VehicleInfoData2
{
	/**
    * Vehicles in list has two turret modules.
    * Format:
    * vehicel name, stock max hp, turret status
    * Turret status: 2 - unable to mount top gun to stock turret, 1 - able
    */
	static public var data : Object;

}